development:
  adapter: postgresql
  encoding: unicode
  database: makerblog
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: makerblog-production
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: makerblog-test
  host: localhost
  port: 5432